title: Jason Mc
description: school assignments and essays
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

author:
  name: Jason Mc

minimal_mistakes_skin: default

# remove extra clutter
breadcrumbs: false
search: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      show_date: true
      
collections:
  8th:
    output: true

header_pages:
  - _8th/index.md
